/*
 * Generated by Dwarf http://code.google.com/p/dwarf27/
 * Support demis27@demis27.net
 */
package org.demis.family.core.datecontainer;

import javax.persistence.*;
import static javax.persistence.FetchType.LAZY;
import java.io.Serializable;
import java.util.List;

import org.apache.log4j.Logger;
import org.demis.family.core.AbstractEntity;
import org.hibernate.annotations.GenericGenerator;

import org.demis.family.core.date.* ;
import org.demis.family.core.event.* ;
import org.demis.family.core.familytree.* ;

@Entity
@Table(name = "date_container")
public class DateContainerEntity extends AbstractEntity {

    private static final Logger logger = Logger.getLogger(DateContainerEntity.class);

    @Column(name = "date_container_id", nullable = false, unique = true, length = 32)
    @GeneratedValue(generator = "strategy-uuid")
    @GenericGenerator(name = "strategy-uuid", strategy = "uuid")
    @Id
    private String id = null;

    @Column(name="mode", nullable=false)
    private java.lang.String mode = null;

    @JoinColumn(name = "family_tree_id")
    @ManyToOne(fetch = LAZY)
    private FamilyTreeEntity familyTree;

    @JoinColumn(name = "first_date_id")
    @ManyToOne(fetch = LAZY)
    private DateEntity firstDate;

    @JoinColumn(name = "second_date_id")
    @ManyToOne(fetch = LAZY)
    private DateEntity secondDate;

    @OneToMany(mappedBy = "event")
    private List<EventEntity> events;

    public DateContainerEntity() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMode() {
        return mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
    }

    public FamilyTreeEntity getFamilyTree() {
        return familyTree;
    }

    public void setFamilyTree(FamilyTreeEntity familyTree) {
        this.familyTree = familyTree;
    }

    public DateEntity getFirstDate() {
        return firstDate;
    }

    public void setFirstDate(DateEntity firstDate) {
        this.firstDate = firstDate;
    }

    public DateEntity getSecondDate() {
        return secondDate;
    }

    public void setSecondDate(DateEntity secondDate) {
        this.secondDate = secondDate;
    }

    public List<EventEntity> getEvents() {
        return events;
    }

    public void setEvents(List<EventEntity> events) {
        this.events = events;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DateContainerEntity that = (DateContainerEntity) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
