/*
 * Generated by Dwarf http://code.google.com/p/dwarf27/
 * Support demis27@demis27.net
 */
package org.demis.family.core.event;

import javax.persistence.*;
import static javax.persistence.FetchType.LAZY;
import java.io.Serializable;

import org.apache.log4j.Logger;
import org.hibernate.annotations.GenericGenerator;

import org.demis.family.core.familytree.* ;
import org.demis.family.core.datecontainer.* ;

@Entity
@Table(name = "event")
public class EventEntity implements Serializable {

    private static final Logger logger = Logger.getLogger(EventEntity.class);

    @Column(name = "event_id", nullable = false, unique = true, length = 32)
    @GeneratedValue(generator = "strategy-uuid")
    @GenericGenerator(name = "strategy-uuid", strategy = "uuid")
    @Id
    private java.lang.String id = null;

    @JoinColumn(name = "family_tree_id")
    @ManyToOne(fetch = LAZY)
    private FamilyTreeEntity familyTree;

    @JoinColumn(name = "date_container")
    @ManyToOne(fetch = LAZY)
    private DateContainerEntity dateContainer;

    public EventEntity() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public FamilyTreeEntity getFamilyTree() {
        return familyTree;
    }

    public void setFamilyTree(FamilyTreeEntity familyTree) {
        this.familyTree = familyTree;
    }

    public DateContainerEntity getDateContainer() {
        return dateContainer;
    }

    public void setDateContainer(DateContainerEntity dateContainer) {
        this.dateContainer = dateContainer;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        EventEntity that = (EventEntity) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
