/*
 * Generated by Dwarf http://code.google.com/p/dwarf27/
 * Support demis27@demis27.net
 */
package org.demis.family.core.date;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import org.apache.log4j.Logger;
import org.demis.family.core.AbstractEntity;
import org.hibernate.annotations.GenericGenerator;

import org.demis.family.core.datecontainer.* ;

@Entity
@Table(name = "\"date\"")
public class DateEntity extends AbstractEntity {

    private static final Logger logger = Logger.getLogger(DateEntity.class);

    @Column(name = "date_id", nullable = false, unique = true, length = 32)
    @GeneratedValue(generator = "strategy-uuid")
    @GenericGenerator(name = "strategy-uuid", strategy = "uuid")
    @Id
    private java.lang.String id = null;

    @Column(name="year", nullable=false)
    private java.lang.Integer year = null;

    @Column(name="month", nullable=false)
    private java.lang.Integer month = null;

    @Column(name="day", nullable=false)
    private java.lang.Integer day = null;

    @Column(name="hour", nullable=false)
    private java.lang.Integer hour = null;

    @Column(name="minute", nullable=false)
    private java.lang.Integer minute = null;

    @Column(name="second", nullable=false)
    private java.lang.Integer second = null;

    public DateEntity() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public Integer getMinute() {
        return minute;
    }

    public void setMinute(Integer minute) {
        this.minute = minute;
    }

    public Integer getSecond() {
        return second;
    }

    public void setSecond(Integer second) {
        this.second = second;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DateEntity that = (DateEntity) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
